server:
  port: 8765

spring:
  application:
    name: custom-feign
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
